const CONCATENATION_OPERATOR = "·";
const UNION_OPERATOR = "|";
const CLOSURE_OPERATOR = "*";
const ZERO_OR_ONE_OPERATOR = "?";
const ONE_OR_MORE_OPERATOR = "+";
const GROUP_LEFT_OPERATOR = "(";
const GROUP_RIGHT_OPERATOR = ")";

module.exports = {
  CONCATENATION_OPERATOR,
  UNION_OPERATOR,
  CLOSURE_OPERATOR,
  ZERO_OR_ONE_OPERATOR,
  ONE_OR_MORE_OPERATOR,
  GROUP_LEFT_OPERATOR,
  GROUP_RIGHT_OPERATOR
}